collectd-agent:
  image: rzarouali/ocm-collectd:latest
  labels:
    io.rancher.container.hostname_override: container_name
  environment:
    GRAPHITE_HOST: ${graphite_host}
    COLLECTD_INTERVAL: ${collectd_interval}
