.catalog:
  name: "Collectd agent"
  version: 1.0.0-rancher1
  description: |
    Custom collectd with pxc and docker support
  questions:
    - variable: "graphite_host"
      type: string
      required: true
      label: "Graphite host"
      description: "Graphite host that will receive metrics"
    - variable: "collectd_interval"
      type: string
      required: true
      label: "Collectd interval"
      description: "interval within collecd collects metrics"
