ranch-eye:
  ports:
  - 9104:9104/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.dns: true
  tty: true
  image: infinityworks/ranch-eye:03
  stdin_open: true
  net: "host"
  environment:
    COLLECTD_DOCKER_APP: "ranch-eye"


graphite-db:
  tty: true
  image: sitespeedio/graphite:latest
  command: cat
  volumes:
    - /opt/graphite/storage/whisper/

graphite:
  image: sitespeedio/graphite:latest
  ports:
    - 8181:80
    - 2003:2003
  labels:
    io.rancher.sidekicks: graphite-db
  volumes_from:
    - graphite-db 
  environment:
    COLLECTD_DOCKER_APP: "graphite"


prometheus-rancher-exporter:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: infinityworks/prometheus-rancher-exporter:04
    environment:
       COLLECTD_DOCKER_APP: "rancher-exporter"

ocm-pmm-server:
    tty: true
    labels:
      io.rancher.container.create_agent: true
      io.rancher.container.agent.role: environment
    image: rzarouali/ocm-pmm-server:latest
    links:
      - ranch-eye:ranch-eye
      - prometheus-rancher-exporter:prometheus-rancher-exporter
    environment:
       COLLECTD_DOCKER_APP: "ocm-pmm-server"
    ports:
      - 80:80